### Send POST request with json body
POST http://localhost:8000/api/v1/issuance/coupons/issue
Content-Type: application/json

{
  "transactionId": "{{$random.uuid}}",
  "productId": "P0001",
  "issuanceQuantity": 100,
  "price": 10000,
  "couponExpiredStart": "20240101000000",
  "couponExpiredEnd": "20240131235959"
}
