### Send POST request with json body
POST http://localhost:8000/api/v1/issuance/coupons/issue
Content-Type: application/json

{
  "transactionId": "test-transaction-id35",
  "productId": "P0001",
  "issuanceQuantity": 10,
  "price": 10000,
  "couponExpiredStart": "20231001000000",
  "couponExpiredEnd": "20231031235959"
}
